using PaperProcessor.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace PaperProcessor.Pdf
{
    public class InvoicePdfDocument : IDocument
    {
        private readonly Invoice _invoice;

        public InvoicePdfDocument(Invoice invoice)
        {
            _invoice = invoice;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Element(ComposeHeader);
                page.Content().Element(ComposeContent);

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by PaperProcessor");
                    x.Span(" • ");
                    x.Span(DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
                });
            });
        }

        private void ComposeHeader(IContainer container)
        {
            // IMPORTANT: Use Column so we can add multiple items safely
            container.Column(col =>
            {
                col.Item().Row(row =>
                {
                    row.RelativeItem().Column(left =>
                    {
                        left.Item().Text("PaperProcessor Factory").FontSize(18).SemiBold();
                        left.Item().Text("Invoice").FontSize(14).Bold();
                    });

                    row.ConstantItem(220).Column(right =>
                    {
                        right.Item().Text($"Invoice No: {_invoice.InvoiceNo}").Bold();
                        right.Item().Text($"Issue Date: {_invoice.IssueDate:yyyy-MM-dd}");
                        right.Item().Text($"Due Date: {_invoice.DueDate:yyyy-MM-dd}");
                        right.Item().Text($"Status: {_invoice.Status}");
                    });
                });

                col.Item().PaddingTop(10).LineHorizontal(1);
            });
        }

        private void ComposeContent(IContainer container)
        {
            var customer = _invoice.WorkOrder?.Customer;
            var product = _invoice.WorkOrder?.ProductCarton;

            container.PaddingTop(10).Column(col =>
            {
                col.Spacing(12);

                // Customer + WorkOrder info
                col.Item().Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text("Bill To").Bold();
                        c.Item().Text(customer?.Name ?? "-");
                        if (!string.IsNullOrWhiteSpace(customer?.Email)) c.Item().Text(customer!.Email!);
                        if (!string.IsNullOrWhiteSpace(customer?.Phone)) c.Item().Text(customer!.Phone!);
                        if (!string.IsNullOrWhiteSpace(customer?.Address)) c.Item().Text(customer!.Address!);
                    });

                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text("Work Order").Bold();
                        c.Item().Text(_invoice.WorkOrder?.WorkOrderNo ?? "-");
                        c.Item().Text($"Product: {product?.Name ?? "-"}");
                        c.Item().Text($"Qty Ordered: {_invoice.WorkOrder?.QuantityOrdered ?? 0}");
                    });
                });

                // Line items table
                col.Item().Text("Line Items").Bold();

                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(6); // Description
                        columns.RelativeColumn(2); // Qty
                        columns.RelativeColumn(2); // Unit Price
                        columns.RelativeColumn(2); // Line Total
                    });

                    table.Header(header =>
                    {
                        header.Cell().Element(HeaderCell).Text("Description");
                        header.Cell().Element(HeaderCell).AlignRight().Text("Qty");
                        header.Cell().Element(HeaderCell).AlignRight().Text("Unit Price");
                        header.Cell().Element(HeaderCell).AlignRight().Text("Line Total");

                        static IContainer HeaderCell(IContainer c) =>
                            c.DefaultTextStyle(x => x.SemiBold())
                             .PaddingTop(6).PaddingBottom(6).PaddingLeft(4).PaddingRight(4)
                             .Background(Colors.Grey.Lighten3);
                    });

                    foreach (var line in _invoice.Lines)
                    {
                        table.Cell().Element(BodyCell).Text(line.Description);
                        table.Cell().Element(BodyCell).AlignRight().Text($"{line.Qty:0.##}");
                        table.Cell().Element(BodyCell).AlignRight().Text($"{line.UnitPrice:0.00}");
                        table.Cell().Element(BodyCell).AlignRight().Text($"{line.LineTotal:0.00}");
                    }

                    static IContainer BodyCell(IContainer c) =>
                        c.BorderBottom(1)
                         .BorderColor(Colors.Grey.Lighten2)
                         .PaddingTop(6).PaddingBottom(6).PaddingLeft(4).PaddingRight(4);
                });

                // Totals
                col.Item().AlignRight().Column(totals =>
                {
                    totals.Item().Row(r =>
                    {
                        r.ConstantItem(140).Text("Subtotal:").SemiBold();
                        r.ConstantItem(120).AlignRight().Text($"{_invoice.Subtotal:0.00}");
                    });

                    totals.Item().Row(r =>
                    {
                        r.ConstantItem(140).Text("Discount:").SemiBold();
                        r.ConstantItem(120).AlignRight().Text($"{_invoice.DiscountAmount:0.00}");
                    });

                    // Padding BEFORE line (QuestPDF version-safe)
                    totals.Item().PaddingTop(4).PaddingBottom(4).LineHorizontal(1);

                    totals.Item().Row(r =>
                    {
                        r.ConstantItem(140).Text("Total (No GST):").Bold();
                        r.ConstantItem(120).AlignRight().Text($"{_invoice.Total:0.00}").Bold();
                    });
                });

                col.Item()
                   .PaddingTop(10)
                   .Text("Notes: No GST applied.")
                   .Italic()
                   .FontSize(10)
                   .FontColor(Colors.Grey.Darken2);
            });
        }
    }
}
