// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaperProcessor.Data;

#nullable disable

namespace PaperProcessor.Migrations
{
    [DbContext(typeof(PaperProcessorContext))]
    [Migration("20251225103358_AddStageLogs")]
    partial class AddStageLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaperProcessor.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PaperProcessor.Models.ProductCarton", b =>
                {
                    b.Property<int>("ProductCartonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCartonId"));

                    b.Property<int>("HeightMm")
                        .HasColumnType("int");

                    b.Property<int>("LengthMm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Style")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("WidthMm")
                        .HasColumnType("int");

                    b.HasKey("ProductCartonId");

                    b.ToTable("ProductCartons");
                });

            modelBuilder.Entity("PaperProcessor.Models.ProductionStage", b =>
                {
                    b.Property<int>("ProductionStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionStageId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ProductionStageId");

                    b.ToTable("ProductionStages");

                    b.HasData(
                        new
                        {
                            ProductionStageId = 1,
                            Name = "Cutting",
                            SortOrder = 1
                        },
                        new
                        {
                            ProductionStageId = 2,
                            Name = "Printing",
                            SortOrder = 2
                        },
                        new
                        {
                            ProductionStageId = 3,
                            Name = "Folding",
                            SortOrder = 3
                        },
                        new
                        {
                            ProductionStageId = 4,
                            Name = "Gluing",
                            SortOrder = 4
                        },
                        new
                        {
                            ProductionStageId = 5,
                            Name = "QC",
                            SortOrder = 5
                        },
                        new
                        {
                            ProductionStageId = 6,
                            Name = "Packing",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("PaperProcessor.Models.StageLog", b =>
                {
                    b.Property<int>("StageLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageLogId"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ProductionStageId")
                        .HasColumnType("int");

                    b.Property<int>("QtyOut")
                        .HasColumnType("int");

                    b.Property<int>("ScrapQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("StageLogId");

                    b.HasIndex("ProductionStageId");

                    b.HasIndex("WorkOrderId", "ProductionStageId")
                        .IsUnique();

                    b.ToTable("StageLogs");
                });

            modelBuilder.Entity("PaperProcessor.Models.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductCartonId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitSellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WorkOrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductCartonId");

                    b.HasIndex("WorkOrderNo")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("PaperProcessor.Models.StageLog", b =>
                {
                    b.HasOne("PaperProcessor.Models.ProductionStage", "ProductionStage")
                        .WithMany()
                        .HasForeignKey("ProductionStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaperProcessor.Models.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionStage");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PaperProcessor.Models.WorkOrder", b =>
                {
                    b.HasOne("PaperProcessor.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaperProcessor.Models.ProductCarton", "ProductCarton")
                        .WithMany()
                        .HasForeignKey("ProductCartonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ProductCarton");
                });
#pragma warning restore 612, 618
        }
    }
}
